"""Pin ALTER routine characteristics against native MySQL 8.4.11."""
import pathlib
import runpy

arguments = runpy.run_path(str(pathlib.Path(__file__).with_name("name-const-oracle.py")))
cases = [
    ("SELECT COLUMN_NAME,COLUMN_TYPE FROM information_schema.columns WHERE TABLE_SCHEMA='information_schema' AND TABLE_NAME='ROUTINES' AND COLUMN_NAME IN ('SQL_DATA_ACCESS','SECURITY_TYPE','SQL_MODE') ORDER BY ORDINAL_POSITION", "COLUMN_NAME\tCOLUMN_TYPE\nSQL_DATA_ACCESS\tenum('CONTAINS SQL','NO SQL','READS SQL DATA','MODIFIES SQL DATA')\nSECURITY_TYPE\tenum('DEFAULT','INVOKER','DEFINER')\nSQL_MODE\tset('REAL_AS_FLOAT','PIPES_AS_CONCAT','ANSI_QUOTES','IGNORE_SPACE','NOT_USED','ONLY_FULL_GROUP_BY','NO_UNSIGNED_SUBTRACTION','NO_DIR_IN_CREATE','NOT_USED_9','NOT_USED_10','NOT_USED_11','NOT_USED_12','NOT_USED_13','NOT_USED_14','NOT_USED_15','NOT_USED_16','NOT_USED_17','NOT_USED_18','ANSI','NO_AUTO_VALUE_ON_ZERO','NO_BACKSLASH_ESCAPES','STRICT_TRANS_TABLES','STRICT_ALL_TABLES','NO_ZERO_IN_DATE','NO_ZERO_DATE','ALLOW_INVALID_DATES','ERROR_FOR_DIVISION_BY_ZERO','TRADITIONAL','NOT_USED_29','HIGH_NOT_PRECEDENCE','NO_ENGINE_SUBSTITUTION','PAD_CHAR_TO_FULL_LENGTH','TIME_TRUNCATE_FRACTIONAL')\n"),('CREATE PROCEDURE alter_p() SELECT 1;CREATE FUNCTION alter_f() RETURNS INT DETERMINISTIC RETURN 1', ''),
 ("ALTER PROCEDURE alter_p COMMENT 'changed';SELECT ROUTINE_COMMENT,SQL_DATA_ACCESS,SECURITY_TYPE FROM "
  "information_schema.routines WHERE ROUTINE_SCHEMA='probe' AND ROUTINE_NAME='alter_p'",
  'ROUTINE_COMMENT\tSQL_DATA_ACCESS\tSECURITY_TYPE\nchanged\tCONTAINS SQL\tDEFINER\n'),
 ("ALTER PROCEDURE alter_p SQL SECURITY INVOKER READS SQL DATA LANGUAGE SQL COMMENT 'it''s changed';SELECT "
  'ROUTINE_COMMENT,SQL_DATA_ACCESS,SECURITY_TYPE FROM information_schema.routines WHERE '
  "ROUTINE_SCHEMA='probe' AND ROUTINE_NAME='alter_p';SHOW CREATE PROCEDURE alter_p",
  'ROUTINE_COMMENT\tSQL_DATA_ACCESS\tSECURITY_TYPE\n'
  "it's changed\tREADS SQL DATA\tINVOKER\n"
  'Procedure\tsql_mode\tCreate Procedure\tcharacter_set_client\tcollation_connection\tDatabase Collation\n'
  'alter_p\t'
  'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION\t'
  'CREATE DEFINER=`root`@`localhost` PROCEDURE `alter_p`()\n'
  '    READS SQL DATA\n'
  '    SQL SECURITY INVOKER\n'
  "    COMMENT 'it''s changed'\n"
  'SELECT 1\tutf8mb4\tutf8mb4_0900_ai_ci\tutf8mb4_0900_ai_ci\n'),
 ("ALTER FUNCTION alter_f SQL SECURITY INVOKER NO SQL COMMENT 'fn';SELECT "
  'ROUTINE_COMMENT,SQL_DATA_ACCESS,SECURITY_TYPE,IS_DETERMINISTIC FROM information_schema.routines WHERE '
  "ROUTINE_SCHEMA='probe' AND ROUTINE_NAME='alter_f';SHOW CREATE FUNCTION alter_f",
  'ROUTINE_COMMENT\tSQL_DATA_ACCESS\tSECURITY_TYPE\tIS_DETERMINISTIC\n'
  'fn\tNO SQL\tINVOKER\tYES\n'
  'Function\tsql_mode\tCreate Function\tcharacter_set_client\tcollation_connection\tDatabase Collation\n'
  'alter_f\t'
  'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION\t'
  'CREATE DEFINER=`root`@`localhost` FUNCTION `alter_f`() RETURNS int\n'
  '    NO SQL\n'
  '    DETERMINISTIC\n'
  '    SQL SECURITY INVOKER\n'
  "    COMMENT 'fn'\n"
  'RETURN 1\tutf8mb4\tutf8mb4_0900_ai_ci\tutf8mb4_0900_ai_ci\n'),
 ("ALTER PROCEDURE alter_p COMMENT 'first' COMMENT 'second';SELECT ROUTINE_COMMENT FROM "
  "information_schema.routines WHERE ROUTINE_SCHEMA='probe' AND ROUTINE_NAME='alter_p'",
  'ROUTINE_COMMENT\nsecond\n'),
 ('ALTER PROCEDURE alter_p DETERMINISTIC', (1064, '42000')),
 ('ALTER FUNCTION alter_f NOT DETERMINISTIC', (1064, '42000')),
 ("ALTER PROCEDURE missing_p COMMENT 'x'", (1305, '42000')),
 ('ALTER PROCEDURE alter_p', ''),
 ("SET sql_mode='ANSI_QUOTES';ALTER PROCEDURE alter_p COMMENT 'mode';SELECT SQL_MODE FROM "
  "information_schema.routines WHERE ROUTINE_SCHEMA='probe' AND ROUTINE_NAME='alter_p'",
  'SQL_MODE\n'
  'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION\n')]


def verify(client, _writer):
    arguments["verify_cases"](client, cases)


if __name__ == "__main__":
    arguments["oracle"]["run"](verify)
