"""Pin malformed text storage conversion against native MySQL 8.4.11."""
import pathlib
import runpy

arguments = runpy.run_path(str(pathlib.Path(__file__).with_name("name-const-oracle.py")))
cases = [
    ("DROP TABLE IF EXISTS encoded_target;CREATE TABLE encoded_target(v VARCHAR(20) CHARACTER SET ascii);SET sql_mode='';INSERT INTO encoded_target VALUES(_ascii X'418042');SHOW WARNINGS;SELECT HEX(v) AS h FROM encoded_target", "Level\tCode\tMessage\nWarning\t1300\tInvalid ascii character string: '8042'\nWarning\t1366\tIncorrect string value: '\\x80B' for column 'v' at row 1\nh\n41\n"),
    ("DROP TABLE IF EXISTS encoded_target;CREATE TABLE encoded_target(v VARCHAR(20) CHARACTER SET utf8mb3);SET sql_mode='';INSERT INTO encoded_target VALUES(_utf8mb3'a😀b');SHOW WARNINGS;SELECT HEX(v) AS h FROM encoded_target", "Level\tCode\tMessage\nWarning\t1287\t'utf8mb3' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nWarning\t1300\tInvalid utf8mb3 character string: 'F09F98'\nWarning\t1366\tIncorrect string value: '\\xF0\\x9F\\x98\\x80b' for column 'v' at row 1\nh\n61\n"),
    ("DROP TABLE IF EXISTS encoded_target;CREATE TABLE encoded_target(v VARCHAR(20) CHARACTER SET utf8mb4);SET sql_mode='';INSERT INTO encoded_target VALUES(_utf8mb3'a😀b');SHOW WARNINGS;SELECT HEX(v) AS h FROM encoded_target", "Level\tCode\tMessage\nWarning\t1287\t'utf8mb3' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nWarning\t1300\tInvalid utf8mb3 character string: 'F09F98'\nWarning\t1366\tIncorrect string value: '\\xF0\\x9F\\x98\\x80b' for column 'v' at row 1\nh\n613F3F3F3F62\n"),
    ("DROP TABLE IF EXISTS encoded_target;CREATE TABLE encoded_target(v VARCHAR(20) CHARACTER SET utf8mb4);SET sql_mode='';INSERT INTO encoded_target VALUES(_ascii X'418042');SHOW WARNINGS;SELECT HEX(v) AS h FROM encoded_target", "Level\tCode\tMessage\nWarning\t1300\tInvalid ascii character string: '8042'\nWarning\t1366\tIncorrect string value: '\\x80B' for column 'v' at row 1\nh\n413F42\n"),
    ("DROP TABLE IF EXISTS encoded_target;CREATE TABLE encoded_target(v VARCHAR(20) CHARACTER SET ascii);SET sql_mode='STRICT_TRANS_TABLES';INSERT INTO encoded_target VALUES(_ascii X'418042');SHOW WARNINGS;SELECT HEX(v) AS h FROM encoded_target", (1366, 'HY000')),
    ("DROP TABLE IF EXISTS encoded_target;CREATE TABLE encoded_target(v VARCHAR(20) CHARACTER SET utf8mb3);SET sql_mode='STRICT_TRANS_TABLES';INSERT INTO encoded_target VALUES(_utf8mb3'a😀b');SHOW WARNINGS;SELECT HEX(v) AS h FROM encoded_target", (1366, 'HY000')),
    ("DROP TABLE IF EXISTS encoded_target;CREATE TABLE encoded_target(v VARCHAR(20) CHARACTER SET utf8mb4);SET sql_mode='STRICT_TRANS_TABLES';INSERT INTO encoded_target VALUES(_utf8mb3'a😀b');SHOW WARNINGS;SELECT HEX(v) AS h FROM encoded_target", (1366, 'HY000')),
    ("DROP TABLE IF EXISTS encoded_target;CREATE TABLE encoded_target(v VARCHAR(20) CHARACTER SET utf8mb4);SET sql_mode='STRICT_TRANS_TABLES';INSERT INTO encoded_target VALUES(_ascii X'418042');SHOW WARNINGS;SELECT HEX(v) AS h FROM encoded_target", (1366, 'HY000')),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(20) CHARACTER SET ucs2);SET sql_mode='';INSERT INTO surrogate_target VALUES(_ucs2 X'0041D8000042');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n FROM surrogate_target", "Level\tCode\tMessage\nWarning\t1287\t'ucs2' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nh\tn\n0041D8000042\t6\n"),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(20) CHARACTER SET utf8mb4);SET sql_mode='';INSERT INTO surrogate_target VALUES(_ucs2 X'0041D8000042');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n FROM surrogate_target", "Level\tCode\tMessage\nWarning\t1287\t'ucs2' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nh\tn\n41EDA08042\t5\n"),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(20) CHARACTER SET ascii);SET sql_mode='';INSERT INTO surrogate_target VALUES(_ucs2 X'0041D8000042');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n FROM surrogate_target", "Level\tCode\tMessage\nWarning\t1287\t'ucs2' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nWarning\t1366\tIncorrect string value: '\\xD8\\x00\\x00\\x42' for column 'v' at row 1\nh\tn\n413F42\t3\n"),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(20) CHARACTER SET ucs2);SET sql_mode='STRICT_TRANS_TABLES';INSERT INTO surrogate_target VALUES(_ucs2 X'0041D8000042');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n FROM surrogate_target", "Level\tCode\tMessage\nWarning\t1287\t'ucs2' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nh\tn\n0041D8000042\t6\n"),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(20) CHARACTER SET utf8mb4);SET sql_mode='STRICT_TRANS_TABLES';INSERT INTO surrogate_target VALUES(_ucs2 X'0041D8000042');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n FROM surrogate_target", "Level\tCode\tMessage\nWarning\t1287\t'ucs2' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nh\tn\n41EDA08042\t5\n"),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(20) CHARACTER SET ascii);SET sql_mode='STRICT_TRANS_TABLES';INSERT INTO surrogate_target VALUES(_ucs2 X'0041D8000042');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n FROM surrogate_target", (1366, 'HY000')),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(1) CHARACTER SET ucs2);SET sql_mode='';INSERT INTO surrogate_target VALUES(_ucs2 X'0041D8000042');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n,CHAR_LENGTH(v) AS c FROM surrogate_target", "Level\tCode\tMessage\nWarning\t1287\t'ucs2' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nWarning\t1265\tData truncated for column 'v' at row 1\nh\tn\tc\n0041\t2\t1\n"),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(2) CHARACTER SET ucs2);SET sql_mode='';INSERT INTO surrogate_target VALUES(_ucs2 X'0041D8000042');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n,CHAR_LENGTH(v) AS c FROM surrogate_target", "Level\tCode\tMessage\nWarning\t1287\t'ucs2' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nWarning\t1265\tData truncated for column 'v' at row 1\nh\tn\tc\n0041D800\t4\t2\n"),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(3) CHARACTER SET ucs2);SET sql_mode='';INSERT INTO surrogate_target VALUES(_ucs2 X'0041D8000042');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n,CHAR_LENGTH(v) AS c FROM surrogate_target", "Level\tCode\tMessage\nWarning\t1287\t'ucs2' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nh\tn\tc\n0041D8000042\t6\t3\n"),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(1) CHARACTER SET ucs2);SET sql_mode='';INSERT INTO surrogate_target VALUES(_ucs2 X'D83DDE00');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n,CHAR_LENGTH(v) AS c FROM surrogate_target", "Level\tCode\tMessage\nWarning\t1287\t'ucs2' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nWarning\t1265\tData truncated for column 'v' at row 1\nh\tn\tc\nD83D\t2\t1\n"),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(2) CHARACTER SET ucs2);SET sql_mode='';INSERT INTO surrogate_target VALUES(_ucs2 X'D83DDE00');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n,CHAR_LENGTH(v) AS c FROM surrogate_target", "Level\tCode\tMessage\nWarning\t1287\t'ucs2' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nh\tn\tc\nD83DDE00\t4\t2\n"),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(3) CHARACTER SET ucs2);SET sql_mode='';INSERT INTO surrogate_target VALUES(_ucs2 X'D83DDE00');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n,CHAR_LENGTH(v) AS c FROM surrogate_target", "Level\tCode\tMessage\nWarning\t1287\t'ucs2' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nh\tn\tc\nD83DDE00\t4\t2\n"),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(1) CHARACTER SET utf8mb4);SET sql_mode='';INSERT INTO surrogate_target VALUES(_ucs2 X'0041D8000042');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n,CHAR_LENGTH(v) AS c FROM surrogate_target", "Level\tCode\tMessage\nWarning\t1287\t'ucs2' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nWarning\t1265\tData truncated for column 'v' at row 1\nh\tn\tc\n41\t1\t1\n"),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(2) CHARACTER SET utf8mb4);SET sql_mode='';INSERT INTO surrogate_target VALUES(_ucs2 X'0041D8000042');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n,CHAR_LENGTH(v) AS c FROM surrogate_target", "Level\tCode\tMessage\nWarning\t1287\t'ucs2' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nWarning\t1265\tData truncated for column 'v' at row 1\nh\tn\tc\n41EDA080\t4\t4\n"),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(3) CHARACTER SET utf8mb4);SET sql_mode='';INSERT INTO surrogate_target VALUES(_ucs2 X'0041D8000042');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n,CHAR_LENGTH(v) AS c FROM surrogate_target", "Level\tCode\tMessage\nWarning\t1287\t'ucs2' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nh\tn\tc\n41EDA08042\t5\t5\n"),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(1) CHARACTER SET utf8mb4);SET sql_mode='';INSERT INTO surrogate_target VALUES(_ucs2 X'D83DDE00');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n,CHAR_LENGTH(v) AS c FROM surrogate_target", "Level\tCode\tMessage\nWarning\t1287\t'ucs2' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nWarning\t1265\tData truncated for column 'v' at row 1\nh\tn\tc\nEDA0BD\t3\t3\n"),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(2) CHARACTER SET utf8mb4);SET sql_mode='';INSERT INTO surrogate_target VALUES(_ucs2 X'D83DDE00');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n,CHAR_LENGTH(v) AS c FROM surrogate_target", "Level\tCode\tMessage\nWarning\t1287\t'ucs2' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nh\tn\tc\nEDA0BDEDB880\t6\t6\n"),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(3) CHARACTER SET utf8mb4);SET sql_mode='';INSERT INTO surrogate_target VALUES(_ucs2 X'D83DDE00');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n,CHAR_LENGTH(v) AS c FROM surrogate_target", "Level\tCode\tMessage\nWarning\t1287\t'ucs2' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nh\tn\tc\nEDA0BDEDB880\t6\t6\n"),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(20) CHARACTER SET ascii);SET sql_mode='';INSERT INTO surrogate_target VALUES(_ucs2 X'0041D83DDE0000420043');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n FROM surrogate_target", "Level\tCode\tMessage\nWarning\t1287\t'ucs2' is deprecated and will be removed in a future release. Please use utf8mb4 instead\nWarning\t1366\tIncorrect string value: '\\xD8\\x3D\\xDE\\x00\\x00\\x42...' for column 'v' at row 1\nh\tn\n413F3F4243\t5\n"),
    ("DROP TABLE IF EXISTS surrogate_target;CREATE TABLE surrogate_target(v VARCHAR(20) CHARACTER SET ascii);SET sql_mode='STRICT_TRANS_TABLES';INSERT INTO surrogate_target VALUES(_ucs2 X'0041D83DDE0000420043');SHOW WARNINGS;SELECT HEX(v) AS h,LENGTH(v) AS n FROM surrogate_target", (1366, 'HY000')),
]

def verify(client, _writer):
    arguments["verify_cases"](client, cases)

if __name__ == "__main__":
    arguments["oracle"]["run"](verify)
