module Fsdb.Privileges

let dynamic =
    [ "FIREWALL_EXEMPT"
      "AUDIT_ABORT_EXEMPT"
      "ALLOW_NONEXISTENT_DEFINER"
      "SENSITIVE_VARIABLES_OBSERVER"
      "AUTHENTICATION_POLICY_ADMIN"
      "GROUP_REPLICATION_STREAM"
      "FLUSH_PRIVILEGES"
      "PASSWORDLESS_USER_ADMIN"
      "FLUSH_TABLES"
      "FLUSH_OPTIMIZER_COSTS"
      "OPTIMIZE_LOCAL_TABLE"
      "INNODB_REDO_LOG_ENABLE"
      "APPLICATION_PASSWORD_ADMIN"
      "REPLICATION_APPLIER"
      "SESSION_VARIABLES_ADMIN"
      "TELEMETRY_LOG_ADMIN"
      "AUDIT_ADMIN"
      "TABLE_ENCRYPTION_ADMIN"
      "SERVICE_CONNECTION_ADMIN"
      "FLUSH_USER_RESOURCES"
      "REPLICATION_SLAVE_ADMIN"
      "CLONE_ADMIN"
      "CONNECTION_ADMIN"
      "SYSTEM_USER"
      "ENCRYPTION_KEY_ADMIN"
      "RESOURCE_GROUP_ADMIN"
      "SHOW_ROUTINE"
      "XA_RECOVER_ADMIN"
      "SET_ANY_DEFINER"
      "ROLE_ADMIN"
      "PERSIST_RO_VARIABLES_ADMIN"
      "BINLOG_ADMIN"
      "BINLOG_ENCRYPTION_ADMIN"
      "BACKUP_ADMIN"
      "GROUP_REPLICATION_ADMIN"
      "TRANSACTION_GTID_TAG"
      "RESOURCE_GROUP_USER"
      "SYSTEM_VARIABLES_ADMIN"
      "FLUSH_STATUS"
      "INNODB_REDO_LOG_ARCHIVE" ]

let private dynamicNames = dynamic |> Set.ofList

let contains (name: string) =
    dynamicNames.Contains(name.ToUpperInvariant())
